export const MonthlyFormData: any = [
  {
    key: "purchaseLocal",
    title: "Purchase LOCAL",
    particulars: "Purchase LOCAL",
    gstType: "cgst/sgst",
    rows: [],
  },
  {
    key: "returnsLocal",
    title: "Returns-LOCAL",
    particulars: "Returns-LOCAL",
    gstType: "cgst/sgst",
    rows: [],
  },
  {
    key: "reversalOfInputCredit",
    title: "Reversal of Input Credit- Sec 42 & 43",
    particulars: "Reversal of Input Credit - Sec 42 & 43",
    gstType: "both",
    rows: [],
  },
  {
    key: "purchaseIgst",
    title: "Purchase IGST",
    particulars: "Purchase IGST",
    gstType: "igst",
    rows: [],
  },
  {
    key: "returnsIgst",
    title: "Returns-IGST",
    particulars: "Returns-IGST",
    gstType: "igst",
    rows: [],
  },
  {
    key: "ineligibleInputCredit",
    title: "Ineligible Input credit - Sec 17(5)",
    particulars: "Ineligible Input credit - Sec 17(5)",
    gstType: "both",
    rows: [],
  },
  {
    key: "saleLocal",
    title: "Sale-LOCAL",
    particulars: "Sale-LOCAL",
    gstType: "cgst/sgst",
    rows: [],
  },
  {
    key: "returnLocal",
    title: "Return-LOCAL",
    particulars: "Return-LOCAL",
    gstType: "cgst/sgst",
    rows: [],
  },
  {
    key: "saleIgst",
    title: "Sale-IGST",
    particulars: "Sale-IGST",
    gstType: "igst",
    rows: [],
  },
  {
    key: "returnIgst",
    title: "Return-IGST",
    particulars: "Return-IGST",
    gstType: "igst",
    rows: [],
  },
  {
    key: "urdPurchase",
    title: "URD Purchase",
    particulars: "URD Purchase",
    gstType: "cgst/sgst",
    rows: [],
  },
  {
    key: "freightLocal",
    title: "Frieght - Local",
    particulars: "Frieght - Local",
    gstType: "cgst/sgst",
    rows: [],
  },
  {
    key: "freightIgst",
    title: "Frieght - IGST",
    particulars: "Frieght - IGST",
    gstType: "igst",
    rows: [],
  },
];
